### ISSUE TITLE
Rename 'ietf-network-slice.yang

### ISSUE THREAD

**Issue by tsaad-dev** [lana-wu/ietf-ns-nbi#12]
Need to rename the file name to be in sync with the module name- otherwise tools are complaining:

pyang -f tree ietf-network-slice.yang
**ietf-network-slice.yang:1: warning: unexpected modulename "ietf-network-slice-service" in ietf-network-slice.yang, should be "ietf-network-slice"**

https://github.com/lana-wu/ietf-ns-nbi/blob/937bd59d4d057af5b240a0aa92f408d954715ee0/ietf-network-slice.yang#L1

**Comment by lana-wu** [comment]
It is planned to update the name after rev-02 draft. Some otn-slicing authors would like to see the diff between the latest model and rev-01 one.
