### ISSUE TITLE
rename 'qos-policy-name' to 'ac-qos-policy-name'

### ISSUE THREAD

**Issue by tsaad-dev** [lana-wu/ietf-ns-nbi#13]
so it is in sync with other ac attributes.

https://github.com/lana-wu/ietf-ns-nbi/blob/937bd59d4d057af5b240a0aa92f408d954715ee0/ietf-network-slice.yang#L626

**Comment by lana-wu** [comment]
https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slice-nbi-yang-02
