### ISSUE TITLE
rename 'ac-tp-ip-address' to 'ac-ip-address'

### ISSUE THREAD

**Issue by tsaad-dev** [lana-wu/ietf-ns-nbi#14]
both ip/prefix need to be in sync.

        leaf ac-tp-ip-address {
          type inet:ip-address;
          description
            "The IP address of the attachment circuit.";
        }
        leaf ac-ip-prefix-length {
          type uint8;
          description
            "The subnet prefix length expressed in bits.";
        }

https://github.com/lana-wu/ietf-ns-nbi/blob/937bd59d4d057af5b240a0aa92f408d954715ee0/ietf-network-slice.yang#L616

**Comment by lana-wu** [comment]
resolved
