### ISSUE TITLE
connection-group meaning and description

### ISSUE THREAD

**Issue by sergiobelotti** [lana-wu/ietf-ns-nbi#17]
In the draft the connection-group concept is defined as one entity encompassing more connectivity-constructs with similar SLO or SLE:
"Section 2 of the draft " IETF Network Slice Connection (NS-Connection-group): When an IETF Network Slice has multiple NS-connections.  **The connections with similar SLO or SLE are treated as one NS-connection group.**  An IETF Network Slice can have one or multiple NS-Connection-groups."

In YANG there is no description at all of what is really a connection-group, and you could define connectivity-constructs belonging to a connection-group with different SLO/SLE with respect what defined for connection-group,  contradicting what is defined in the text of the draft.

**Comment by sergiobelotti** [comment]
In one of the last weekly call, it seems to me there was a proposal for new text regarding NS-Connection-groups. I think would be beneficial to put the text here in github so that everyone can suggest possible modifications, if needed.

**Comment by lana-wu** [comment]
Hi, here is the proposed new text:
Connection-group can include one or more connectivity constructs, which can be used in a variety of ways, 
for example, can be used to assign a same SLO/SLE policy to multiple connectivity constructs, 
or to combine multiple connectivity constructs to support some common service types, such as bidirectional unicast service, multipoint-to-point (MP2P) service, hub-and-spoke service etc., or to share some SLO limits within connectivity constructs.

**Comment by lana-wu** [comment]
@sergiobelotti : 

- The idea of the second option is to support customer-enhanced service types other than the basic connectivity construct type. If the “common service type” is not clear enough, I am open to better wording.

- On the third point, I agree this is not clear, which is from one of the case that @tsaad-net  Tarek proposed. Let's have more discussion if we decide to add this. My suggestion is not limiting the purpose of the connection groups, something like below：
Connection-group is an arbitrary collection of one or more connection constructs, which can be used for the following possible purposes:
	Assign a same SLO/SLE policy to multiple connectivity constructs
	Combine multiple connectivity constructs to support some useful service types, such as bidirectional unicast service, multipoint-to-point (MP2P) service, hub-and-spoke service etc.

**Comment by lana-wu** [comment]
@sergiobelotti The current model defines an identity “service-slo-shared-bandwidth”, which can be used for a connection-group SLO
  identity service-slo-shared-bandwidth {
    base service-slo-metric-type;
    description
      "The shared SLO bandwidth bound. It is the limit on the
       bandwidth that can be shared amongst a group of
       connectivity constructs of a slice service.";
  }

**Comment by sergiobelotti** [comment]
> @sergiobelotti :
> 
> * The idea of the second option is to support customer-enhanced service types other than the basic connectivity construct type. If the “common service type” is not clear enough, I am open to better wording.

SB> Looking at the framework document section 3.2 it seems to me that what you mention as "customer-enhanced service types" can be realized in different ways using the already define set of connectivity-constructs types. Is in the spirit of this NBI draft dealing with "realization" ? My understanding is not . Instead if my understanding of your explanation is correct the intention is to use connection group to provide a realization of more complex types of connectivity  (like MP2MP) or traffic flow like bidirectional unicast service . Is correct my summary? 
 
> * On the third point, I agree this is not clear, which is from one of the case that @tsaad-net  Tarek proposed. Let's have more discussion if we decide to add this. My suggestion is not limiting the purpose of the connection groups, something like below：
SB> The problem is not limiting the concept, the problem is to have in mind what is the original intention to define a connection-group. It seems to me that the original intention was to encompass a set of connectivty-construct sharing the same SLO/SLE . Full stop. 
Since in the framework there is no connection-group definition that should be clearly defined .
>   Connection-group is an arbitrary collection of one or more connection constructs, which can be used for the following possible purposes:
>   	Assign a same SLO/SLE policy to multiple connectivity constructs
>   	Combine multiple connectivity constructs to support some useful service types, such as bidirectional unicast service, multipoint-to-point (MP2P) service, hub-and-spoke service etc.

**Comment by lana-wu** [comment]
Yes. The intention here is to use connection group to provide a more **complex types of connectivity** (like MP2MP) or traffic flow like bidirectional unicast service. But not sure about the "realization" you mentioned, my understanding the complex service types described in the framework draft is also a requirement.
