### ISSUE TITLE
When “match-type” is “service-flow-match”, how can we support complex combinations of IP packet headers?

### ISSUE THREAD

**Issue by lana-wu** [lana-wu/ietf-ns-nbi#20]
Possible options:
1. Add a leafref of ACL name 
2. Explicitly define various combinations, like L3SM definition
 +--rw rule* [id]
    +--rw id                         string
    +--rw (match-type)?
    |  +--:(match-flow)
    |  |  +--rw match-flow
    |  |     +--rw dscp?                inet:dscp
    |  |     +--rw dot1p?               uint8
    |  |     +--rw ipv4-src-prefix?     inet:ipv4-prefix
    |  |     +--rw ipv6-src-prefix?     inet:ipv6-prefix
    |  |     +--rw ipv4-dst-prefix?     inet:ipv4-prefix
    |  |     +--rw ipv6-dst-prefix?     inet:ipv6-prefix
    |  |     +--rw l4-src-port?         inet:port-number
    |  |     +--rw target-sites*        svc-id {target-sites}?
    |  |     +--rw l4-src-port-range
    |  |     |  +--rw lower-port?   inet:port-number
    |  |     |  +--rw upper-port?   inet:port-number
    |  |     +--rw l4-dst-port?         inet:port-number
    |  |     +--rw l4-dst-port-range
    |  |     |  +--rw lower-port?   inet:port-number
    |  |     |  +--rw upper-port?   inet:port-number
    |  |     +--rw protocol-field?      union
    |  +--:(match-application)
    |     +--rw match-application?   identityref

**Comment by dhruvdhody** [comment]
My strong preference is to start with ACL. RFC 8519 is rich with various attributes we need to match to a flow. 

The 2nd option is also linked with the Opaque string values in YANG v/s keeping the technology-agnostic nature of the NBI model.  TODO: Add a link to that issue HERE.

**Comment by lana-wu** [comment]
[draft-ietf-teas-ietf-network-slice-nbi-yang-03](https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slice-nbi-yang-03)

```
identity service-acl-match {
       base service-match-type;
       description
         "Use Access Control List (ACL) as match criteria
          for the slice service traffic, .";
       reference
         "[RFC 8519](https://datatracker.ietf.org/doc/html/rfc8519): YANG Data Model for
          Network Access Control Lists (ACLs)";
     }
```
