### ISSUE TITLE
“opaque” attributes definition may cause interoperability difficult

### ISSUE THREAD

**Issue by lana-wu** [lana-wu/ietf-ns-nbi#23]
Italo raised some concerns with the current definitions of “opaque” attributes using name/value pairs.
Using the “opaque” attributes will make interoperability at the NSC NBI more difficult and suggest to use existing YANG mechanisms (e.g., augmentations).

**Comment by dhruvdhody** [comment]
Plan to ask for more feedback from the WG and Yang-Doctors on how to balance the technology-agnostic nature of the model v/s the issue pointed out above.

**Comment by lana-wu** [comment]
Same issue with #24

**Comment by agva123** [comment]
Question related to opaque attributes are also posted to the mailing list:
[TEAS mailing list thread](https://mailarchive.ietf.org/arch/msg/teas/msSHR72be8zXH1Prg9qGicywPAw/)

**Comment by lana-wu** [comment]
Addressed in rev-04
