### ISSUE TITLE
Handling of custom topology as input in the NBI (similar to VN Type 2)

### ISSUE THREAD

**Issue by dhruvdhody** [lana-wu/ietf-ns-nbi#25]
To handle this requirement, I suggest the following change - 
````
module: ietf-network-slice-service
  +--rw network-slice-services
  |    ...
     +--rw slice-service* [service-id]
        +--rw service-id                      string
        +--rw service-description?            string
        |    ...
        +--rw (slo-sle-policy)?
        |  +--:(standard)
        |  |  +--rw slo-sle-template?         leafref
        |  +--:(custom)
        |     +--rw service-slo-sle-policy
        |        +--rw policy-description?     string
        |        +--rw metric-bounds
        |        |  +--rw metric-bound* [metric-type]
        |        |     +--rw metric-type          identityref
        |        |     +--rw metric-unit          string
        |        |     +--rw value-description?   string
        |        |     +--rw bound?               uint64
        |        +--rw security*               identityref
        |        +--rw isolation?              identityref
        |        +--rw max-occupancy-level?    uint8
        |        +--rw mtu?                    uint16
        |        +--rw steering-constraints
        |           +--rw path-constraints
        |           +--rw service-function
        +--rw topo
        |  +--rw te-topology-identifier
        |  |  +--rw provider-id?   te-global-id
        |  |  +--rw client-id?     te-global-id
        |  |  +--rw topology-id?   te-topology-id
        |  +--rw abstract-node?
        |          -> /nw:networks/network/node/tet:te-node-id
````

I decided to add this outside of the grouping because repeating it in other places made little sense to me and thus kept it only at the slice level. 

And next, we would need to add a reference to the connectivity-matrix-id from the TE topology as - 

````
        +--rw connection-groups
           +--rw connection-group* [connection-group-id]
              +--rw connection-group-id             string
              +--rw connectivity-type?              identityref
              +--rw (slo-sle-policy)?
              | ...
              +--rw connectivity-construct* [cc-id]
              |  +--rw cc-id                                uint32
              |  +--rw (connectivity-construct-type)?
              | ...
              |  +--rw (slo-sle-policy)?
              |  | ...
              |  +--rw topo
              |  |  +--rw connectivity-matrix*
              |  |          [connectivity-matrix-id]
              |  |     +--rw connectivity-matrix-id    leafref
              |  |     +--rw sender-sdp?
              |  |     |       -> ../../../../../../sdps/sdp/sdp-id
              |  |     +--rw receiver-sdp?
              |  |             -> ../../../../../../sdps/sdp/sdp-id
````
I kept a generic list of connectivity matrix id as the TE topology only supports one source and one destination and any connectivity construct type needs to map to this! 

This would be the minimal change and align with the VN model already adopted in the TEAS WG!

**Comment by lana-wu** [comment]
Let's also have a look at https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-yang-otn-slicing-02#section-5.2.2

   module: ietf-transport-network-slice
     augment /ietf-nss:network-slice-services/ietf-nss:slice-service:
       +--rw network-topologies
          +--rw network-topology* [topology-id]
             +--rw topology-id       string
             +--rw slo-sle-policy
             |  +--rw optimization-criterion?   identityref
             |  +--rw delay-tolerance?          boolean
             |  +--rw periodicity*              uint64
             |  +--rw isolation-level?          identityref
             +--rw node* [node-id]
             |  +--rw node-id              inet:uri
             |  +--rw slo-sle-policy
             |  |  +--rw optimization-criterion?   identityref
             |  |  +--rw delay-tolerance?          boolean
             |  |  +--rw periodicity*              uint64
             |  |  +--rw isolation-level?          identityref
             |  +--rw termination-point* [tp-id]
             |     +--rw tp-id     inet:uri
             |     +--rw sdp-id?   leafref
             +--rw link* [link-id]
                +--rw link-id           inet:uri
                +--rw slo-sle-policy
                |  +--rw optimization-criterion?   identityref
                |  +--rw delay-tolerance?          boolean
                |  +--rw periodicity*              uint64
                |  +--rw isolation-level?          identityref
                +--rw source
                |  +--rw source-node?   -> ../../../node/node-id
                |  +--rw source-tp?     leafref
                +--rw destination
                   +--rw dest-node?   -> ../../../node/node-id
                   +--rw dest-tp?     leafref
     augment /ietf-nss:network-slice-services/ietf-nss:slice-service
               /ietf-nss:connection-groups/ietf-nss:connection-group
               /ietf-nss:connectivity-construct:
       +--rw topology-id?     leafref
       +--rw explicit-path* [tp-id]
          +--rw tp-id    leafref

**Comment by aguoietf** [comment]
As a reference, please see the attached notes from this week's OTN slicing call on topology modeling.
[topology modeling discussion.pptx](https://github.com/lana-wu/ietf-ns-nbi/files/10141945/topology.modeling.discussion.pptx)

**Comment by lana-wu** [comment]
@aguoietf  Per the call on Dec. 05,  to cover non-TE scenarios, "custom-topology" definition in rev-03 will be replaced with generic “network-id”  in stead of “te-topology-id”.
