### ISSUE TITLE
SLO/SLE policy inheritance options

### ISSUE THREAD

**Issue by tsaad-dev** [lana-wu/ietf-ns-nbi#26]
Add support for SLO/SLE policy inheritance options.

**Comment by tsaad-dev** [comment]
parent is template
   child is custom
-> both inherit-override and inherit-update apply

parent is template
   child is template
-> does both make sense? override (?)?

parent is custom
  child is custom

parent {SLO-DELAY=100, SLO-BW=10, SLO-W, SLO-X}
  child1 (default=inherit-override)  {SLO-DELAY=75, SLO-BW=15} --- child3 (inherit-update) {SLO-DELAY=10}
     child2 (update) {SLO-BW=20,SLO-DV=120}
         [SLO-DELAY=75, SLO-BW=20, SLO-DV=120]

parent (well-known template)
  child (no policy)

**Comment by lana-wu** [comment]
[draft-ietf-teas-ietf-network-slice-nbi-yang-03](https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slice-nbi-yang-03#section-5)
```
   +--rw connection-groups
         |  +--rw connection-group* [connection-group-id]
...
         |     +--rw service-slo-sle-policy-override?
         |     |       identityref
...
         |     +--rw connectivity-construct* [cc-id]
         |     |  +--rw cc-id
         |     |  |       uint32
...
         |     |  +--rw service-slo-sle-policy-override?
         |     |  |       identityref

```
