### ISSUE TITLE
Possible bug in match-criteria connection-group leafref

### ISSUE THREAD

**Issue by jmullool** [lana-wu/ietf-ns-nbi#28]
I think there is a bug in the IETF draft under match-criteria for referencing the target-connection-group?

If you look at the yang tree you can see the leafref path is absolute, so it's looking at across all of the slices connection-groups

target-connection-group-id    -> /network-slice-services/slice-service/connection-groups/connection-group/connection-group-id

Shouldn't we only be looking at the connection group from within the slice itself?

**Comment by lana-wu** [comment]
#35 need to be discussed together, in what use cases need AC specific match-criteria? I tend to agree with Sergio that AC specific “service-match-criteria” can be removed.

**Comment by lana-wu** [comment]
[draft-ietf-teas-ietf-network-slice-nbi-yang-03](https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slice-nbi-yang-03#section-6)
Fixed
