### ISSUE TITLE
Should we have both ingress and egress qos-policy names on AC? 

### ISSUE THREAD

**Issue by jmullool** [lana-wu/ietf-ns-nbi#29]
Under attachment-circuit we have "ac-qos-policy-name".

Should we split this into two pieces to cover both ingress and egress policies?

"ac-ingress-qos-policy-name" 
"ac-egress-qos-policy-name"

**Comment by lana-wu** [comment]
Agree with you on this. We can fix this in the next revision.

**Comment by lana-wu** [comment]
[draft-ietf-teas-ietf-network-slice-nbi-yang-03](https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slice-nbi-yang-03#section-6)
Fixed
