### ISSUE TITLE
Concepts of "connection group" and "connectivity construct"

### ISSUE THREAD

**Issue by sergiobelotti** [lana-wu/ietf-ns-nbi#31]
My original understanding of the scope of connectivity group was to add the possibility for a group of network-constructs to share a common SLO. Then other characteristics have been added to connectivity-group like:
-Combine multiple connectivity constructs to support some well-known connectivity types, such as bidirectional unicast service, multipoint-to-point (MP2P) service, hub-and-spoke service etc.
- Share specific SLO limits within multiple connectivity constructs.
- Permit to that a connectivity-construct belonging to one connection-group to redefine slo-sle-policy originally defined in the connection-group i.e. connectivity-construct defined policies have priority over the policy shared in the group.
But I was always supposing that the basic entity was the connectivity-construct and that connection-group would be an option.
Instead, it seems to be a mandatory concept. Connective constructs are defined in the context of a connection group, not as standalone things.

For example: how to specify a hub-and spoke VPN? Looking at example in Appendix 3  the parameter that defines whether an SDP is a hub or a spoke is a connection group attribute, not an attribute of a connectivity construct . 
This is fundamentally wrong if the connection group consists of multiple connectivity constructs: an SDP could be a hub for one connectivity construct, but a spoke for another.

**Comment by lana-wu** [comment]
As defined in NS framework, a connectivity construct has only 3 types: uni-directional P2P, uni-directional P2MP, and any-to-any. Therefore,  SDP role in a connectivity construct is always determined and no need to be specified.
              |  +--rw (connectivity-construct-type)?
              |  |  +--:(p2p)
              |  |  |  +--rw p2p-sender-sdp?
              |  |  |  |       -> ../../../../sdps/sdp/sdp-id
              |  |  |  +--rw p2p-receiver-sdp?
              |  |  |          -> ../../../../sdps/sdp/sdp-id
              |  |  +--:(p2mp)
              |  |  |  +--rw p2mp-sender-sdp?
              |  |  |  |       -> ../../../../sdps/sdp/sdp-id
              |  |  |  +--rw p2mp-receiver-sdp*
              |  |  |          -> ../../../../sdps/sdp/sdp-id
              |  |  +--:(a2a)
              |  |     +--rw a2a-sdp* [sdp-id]
              |  |        +--rw sdp-id
              |  |        |       -> ../../../../../sdps/sdp/sdp-id

**Comment by sergiobelotti** [comment]
> As defined in NS framework, a connectivity construct has only 3 types: uni-directional P2P, uni-directional P2MP, and any-to-any. Therefore, SDP role in a connectivity construct is always determined and no need to be specified. | +--rw (connectivity-construct-type)? | | +--:(p2p) | | | +--rw p2p-sender-sdp? | | | | -> ../../../../sdps/sdp/sdp-id | | | +--rw p2p-receiver-sdp? | | | -> ../../../../sdps/sdp/sdp-id | | +--:(p2mp) | | | +--rw p2mp-sender-sdp? | | | | -> ../../../../sdps/sdp/sdp-id | | | +--rw p2mp-receiver-sdp* | | | -> ../../../../sdps/sdp/sdp-id | | +--:(a2a) | | +--rw a2a-sdp* [sdp-id] | | +--rw sdp-id | | | -> ../../../../../sdps/sdp/sdp-id

I do not think your comment is answering my question: could you please tell me how in the actual model could address the case of hub-and spoke VPN in case the connection group consists of multiple connectivity constructs ? How you can model the fact that an SDP could be a hub for one connectivity construct, but a spoke for another ?

**Comment by tsaad-dev** [comment]
As discussed during the call, the connectivity group-ID serves as a single reference to multiple connectivity-constructs that are part of the group.

For example, we can have two connection-groups (e.g. each realizing hub-n-spoke topology):
- matrix1 - latency < 200ms
- matrix2 - latency < 500ms
An sender SDP may send traffic match1 to connection-group 'matrix1' and traffic match2 to 'matrix2'.
Without this, sender-SDP will have to have a match critera to direct traffic to each and every connectivity construct in the group. This will make the number of entries in match criteria be coupled with number of connnectivity-constructs in the group.

**Comment by sergiobelotti** [comment]
> 



> As discussed during the call, the connectivity group-ID serves as a single reference to multiple connectivity-constructs that are part of the group.
> 
> For example, we can have two connection-groups (e.g. each realizing hub-n-spoke topology):
> 
> * matrix1 - latency < 200ms
> * matrix2 - latency < 500ms
>   An sender SDP may send traffic match1 to connection-group 'matrix1' and traffic match2 to 'matrix2'.
>   Without this, sender-SDP will have to have a match critera to direct traffic to each and every connectivity construct in the group. This will make the number of entries in match criteria be coupled with number of connnectivity-constructs in the group.

This is a very good example of the useful scope of "target-connection-group-id " attribute, for which I have no problem at all. l
See issue #32

**Comment by lana-wu** [comment]
Can we close this issue if #32 is resolved? Or do you see additional text needed?

**Comment by sergiobelotti** [comment]
> Can we close this issue if #32 is resolved? Or do you see additional text needed?

@lana-wu : let me say that the two things are separate issues. Issue #32 simply suggest to delete the target-connectivity-construct-id since  redundant , while, as shown in Tarek's example, target-connection-group-id is essential. I notices that the connectivity-construct-id is optional so I leave to you and the group the decision if to maintain that attribute or delete form the model.

**Comment by sergiobelotti** [comment]
> Can we close this issue if #32 is resolved? Or do you see additional text needed?

@lana-wu : let me say that the two things are separate issues. Issue #32 simply suggest to delete the target-connectivity-construct-id since  redundant , while, as shown in Tarek's example, target-connection-group-id is essential.

**Comment by sergiobelotti** [comment]
@lana-wu : about this issue as I tried to explain in the description my preferred solution would be to have a separate list for connectivity-construct that would be stand-alone entities and you would have a connection group defined with simple pointer to the list of connectivity-construct. Since I understand this would be a significant departure from the model I am ok with specifying CCs within the context of a connection group.
I would just suggest these modifications at the model: 
- regarding hub&spoke, I wold suggest to extend the connectivity-type at connectivity-construct level adding A2A-mesh (as today) and A2A-hub&spoke. Whether to introduce a new type of CC or to enhance the current A2A definition by adding **connectivity-type and sdp-role** as attributes  does not matter much.  Practically my proposal is to move hub&spoke definition at CC level not at the connection-group as today. As I said above the actual model is defining the connection group as a hub-and-spoke VPN, but then identifies P2P and P2MP CCs as the underlying constructs. This is wrong. A hub-and-spoke VPN is not the same as a P2MP construct, the latter is multi-cast interface , the former is not .

**Comment by lana-wu** [comment]
> @lana-wu : about this issue as I tried to explain in the description my preferred solution would be to have a separate list for connectivity-construct that would be stand-alone entities and you would have a connection group defined with simple pointer to the list of connectivity-construct. Since I understand this would be a significant departure from the model I am ok with specifying CCs within the context of a connection group. I would just suggest these modifications at the model:
> 
> * regarding hub&spoke, I wold suggest to extend the connectivity-type at connectivity-construct level adding A2A-mesh (as today) and A2A-hub&spoke. Whether to introduce a new type of CC or to enhance the current A2A definition by adding **connectivity-type and sdp-role** as attributes  does not matter much.  Practically my proposal is to move hub&spoke definition at CC level not at the connection-group as today. As I said above the actual model is defining the connection group as a hub-and-spoke VPN, but then identifies P2P and P2MP CCs as the underlying constructs. This is wrong. A hub-and-spoke VPN is not the same as a P2MP construct, the latter is multi-cast interface , the former is not .

Here is some thought: 
1) The Hub&Spoke is not a single connectivity construct, but multiple CCs. In addition, the NS framework only defines 3 basic CC types.
2）The SDP role in connection group of H&S can be both as sender or receiver, similar with any-to-any connectivity construct.
3) The connectivity constructs of Hub&spoke connection group can be automatically created (which is implicitly), 
and they can also to be specified through a list of P2P CCs and A2A CCs.

**Comment by lana-wu** [comment]
@sergiobelotti Do you still insist this suggestion? I have provided my comments above.

**Comment by swamy-b** [comment]
> > @lana-wu : about this issue as I tried to explain in the description my preferred solution would be to have a separate list for connectivity-construct that would be stand-alone entities and you would have a connection group defined with simple pointer to the list of connectivity-construct. Since I understand this would be a significant departure from the model I am ok with specifying CCs within the context of a connection group. I would just suggest these modifications at the model:
> > 
> > * regarding hub&spoke, I wold suggest to extend the connectivity-type at connectivity-construct level adding A2A-mesh (as today) and A2A-hub&spoke. Whether to introduce a new type of CC or to enhance the current A2A definition by adding **connectivity-type and sdp-role** as attributes  does not matter much.  Practically my proposal is to move hub&spoke definition at CC level not at the connection-group as today. As I said above the actual model is defining the connection group as a hub-and-spoke VPN, but then identifies P2P and P2MP CCs as the underlying constructs. This is wrong. A hub-and-spoke VPN is not the same as a P2MP construct, the latter is multi-cast interface , the former is not .
> 
> Here is some thought:
> 
> 1. The Hub&Spoke is not a single connectivity construct, but multiple CCs. In addition, the NS framework only defines 3 basic CC types.
>    2）The SDP role in connection group of H&S can be both as sender or receiver, similar with any-to-any connectivity construct.
> 2. The connectivity constructs of Hub&spoke connection group can be automatically created (which is implicitly),
>    and they can also to be specified through a list of P2P CCs and A2A CCs.

My thoughts on this. While the Hub&Spoke can be achieved by the multiple CC, it may be inefficient when the are large number of SDP. In that the H&S as a special case of A2A makes sense.

**Comment by lana-wu** [comment]
Addressed in rev-04
