### ISSUE TITLE
What is the need of "target-connectivity-construct-id" attribute in the match-criterion list?

### ISSUE THREAD

**Issue by sergiobelotti** [lana-wu/ietf-ns-nbi#32]
The current model contains the following:
|     +--rw service-match-criteria
        |     |     |  +--rw match-criterion* [index]
        |     |     |     +--rw index
        |     |     |     |       uint32
        |     |     |     +--rw match-type?
        |     |     |     |       identityref
        |     |     |     +--rw value*
        |     |     |     |       string
        |     |     |     +--rw target-connection-group-id?         leafref
        |     |     |     +--rw connection-group-sdp-role?
        |     |     |     |       identityref
        |     |     |     +--rw target-connectivity-construct-id?   
 
In my view the last statement should be removed. The match-criteria should map to a connection group only, not to the combination of a connection group and a connectivity construct. If you look at the examples in the appendix, the only place where the reference to the connectivity construct is relevant is in the example in A4, where the dscp is used to distinguish between slo-sle policies. However, in that case, the model could have defined two different connection groups, one for low latency and one for best effort. There is no need to refer to a connectivity construct within a connection group.

**Comment by lana-wu** [comment]
"target-connectivity-construct-id" is for more flexibility, but I agree that multiple connection-groups can be used for same purpose. Let‘s see whether there is any objection.

**Comment by lana-wu** [comment]
@sergiobelotti Do you still object this definition? I think the Example-4 is clear.

**Comment by lana-wu** [comment]
As discussed in #31, this is closed as "target-connectivity-construct-id" is optional node, which is useful in some particular example, such as appendix Example-4.
