### ISSUE TITLE
How to use A2A as a default

### ISSUE THREAD

**Issue by sergiobelotti** [lana-wu/ietf-ns-nbi#33]
How to use A2A as a default (i.e. the A2A spec applying to all flows that are not addressed by the preceding connectivity constructs) needs to be specified unambiguously in some text in the draft.
Appendix A.5 (with examples A.5.1 and A..2) is addressing this type of situation and it would be good to add text to clarify the usage  of A2A as default.

**Comment by lana-wu** [comment]
Could you describe the use case why this is needed?  Is “service-any-match” is what you are refering?
```
  identity service-match-type {
    description
      "Base identity for IETF Network Slice service traffic
       match type.";
  }
  
  identity service-any-match {
    base service-match-type;
    description
      "Match all slice service traffic.";
  }  

        |     +--rw service-match-criteria
        |     |  +--rw match-criterion* [index]
        |     |     +--rw index
        |     |     |       uint32
        |     |     +--rw match-type
        |     |     |       identityref
        |     |     +--rw value*
        |     |     |       string
        |     |     +--rw target-connection-group-id          leafref
        |     |     +--rw connection-group-sdp-role?
        |     |     |       identityref
        |     |     +--rw target-connectivity-construct-id?   leafref
```

**Comment by sergiobelotti** [comment]
I'm referring simply to what is described in section A.5, where the use case described  is the situation where one slo-sle policy applies to most “connections” within an A2A construct but where special policies apply to a subset. The proposed solution: first, specify the connectivity constructs for which the special policies apply and then have the entire A2A construct with the applicable policy at the end. The suggestion is just to add some text describing e.g. preceding policy, in case as this one  you have A2A as default and some exception.  Hope this clarify my suggestion.

**Comment by lana-wu** [comment]
Thank you for the suggestion. 
How about we add some text in [5.2.3](https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slice-nbi-yang-02#section-5.2.3). to quote the example in A.5. to show the usage of the preceding policy?

**Comment by sergiobelotti** [comment]
> Thank you for the suggestion. How about we add some text in [5.2.3](https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slice-nbi-yang-02#section-5.2.3). to quote the example in A.5. to show the usage of the preceding policy?

@lana-wu : I agree, good idea.

**Comment by lana-wu** [comment]
[draft-ietf-teas-ietf-network-slice-nbi-yang-03](https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slice-nbi-yang-03#section-5.2.3)
Fixed
