### ISSUE TITLE
Usage of  multiple overlapping (in terms of SDPs) A2A constructs

### ISSUE THREAD

**Issue by sergiobelotti** [lana-wu/ietf-ns-nbi#34]
The section A.5 of the draft is addressing the case of A2A and how you can differentiate the traffic flow management in the SDPs .
In particular A.5.2 is showing the usage of multiple overlapping (in terms of SDPs) A2A constructs, with 2 A2A connectivity constructs with different slo-sle policy applied to the same set of SDPs.
I think the usage of multiple A2A CC, is error-prone and a combination of P2P connectivity construct and one final A2A CC it would be the better way to go.

**Comment by lana-wu** [comment]
@tsaad-dev can you comment on this? 
My understanding is the model allows this, but as Sergio points out, it is indeed a bidirectional P2P connection between Hub SDPs

**Comment by lana-wu** [comment]
@sergiobelotti Could you check whether the updated section 5 has addressed this issue? The A.5.2  has been removed since this seems redundant with A.5.1 and is also error-prone

**Comment by sergiobelotti** [comment]
> @sergiobelotti Could you check whether the updated section 5 has addressed this issue? The A.5.2 has been removed since this seems redundant with A.5.1 and is also error-prone [[A.5](https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slice-nbi-yang-03#appendix-A.5).
@lana-wu  OK for me, thanks.
