### ISSUE TITLE
Problem with examples in Appendix A.5

### ISSUE THREAD

**Issue by sergiobelotti** [lana-wu/ietf-ns-nbi#36]
A few comments on section A.5 , with the two examples A.5.1 and A.5.2.

- editorial: in A.5.1 , if I understood correctly the example, at the beginning the text sounds not correct: it says "a uniform low-bandwidth slo-sle-template policy applied to SDP2, SDP3..." but SDP2 is part of the exception with respect the "low-BW-template" so I guess the text should "...applied to SDP4, SDP3"
- the two example are confusing : looking at the title in A.5 , I would expect the the example are referring to two different ways to obtain the same result , or with a single A2A construct with exception inside the connectivity construct or with two overlapping A2A connectivity construct (I have already another comment  related to this aspect) . But in fact we do not reach the same result: it you take as example the traffic exchanged between SDP1 and SDP3. I would interpret this in this way:

1. In A.5.1 , traffic from SDP1 to SDP3 would be under high-BW-template, traffic from SDP3 to SDP1 is governed by the low-BW-template (the reference template in connection-group)
2. in A.5.2, traffic from SDP1 to SDP3 is governed by the low-BW template; traffic from SDP3 to SDP1 is governed by the low-BW template because internal to A2A CC cc-id=2

**Comment by lana-wu** [comment]
Thank you for the review. Will correct this in the next revision.

**Comment by lana-wu** [comment]
@sergiobelotti The A.5.2 has been removed and the editorial issue has been fixed.
[](https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slice-nbi-yang-03#appendix-A.5)
