### ISSUE TITLE
IP prefix matching criteria

### ISSUE THREAD

**Issue by sergiobelotti** [lana-wu/ietf-ns-nbi#39]
I was happen to see a slicing proposal implementation in which the slice matching criteria was based on an IP prefix instead of the full IP address.
Do you think it would be needed to add a new identity e.g. service-source-ip-prefix-match covering IP prefix match or IP address has to be just a specific IP address as it is now?

**Comment by dhruvdhody** [comment]
The description should not use "ip address" instead use "IP prefix"!

**Comment by sergiobelotti** [comment]
> How about the following changes:
> 
> identity service-source-ip-prefix-match { base service-match-type; description "Use source ip address as match criteria for the slice service traffic."; }
> 
> identity service-destination-ip-prefix-match { base service-match-type; description "Use destination ip address as match criteria for the slice service traffic."; }

@lana-wu it's fine but see what Dhruv suggested

**Comment by lana-wu** [comment]
Fixed in the updated model [draft-ietf-teas-ietf-network-slice-nbi-yang-03#section-6](https://datatracker.ietf.org/doc/html/draft-ietf-teas-ietf-network-slice-nbi-yang-03#section-6)

`     identity service-source-ip-prefix-match {
       base service-match-type;
       description
         "Use source ip prefix as match criteria for the slice service
          traffic. Examples of 'value' of this match type is
          '192.0.2.0/24' and '2001:db8::1/64'.";
     }

     identity service-destination-ip-prefix-match {
       base service-match-type;
       description
         "Use destination ip prefix as match criteria for the slice
          service traffic. Examples of 'value' of this match type is
          '203.0.113.1/32', '2001:db8::2/128'.";
     }
`
