### ISSUE TITLE
IP address notation

### ISSUE THREAD

**Issue by sergiobelotti** [lana-wu/ietf-ns-nbi#40]
In YANG definition, in the matching criteria, the match value is a string.  So in case of IP address you can have multiple options to identify that e.g. “137.35.2.5”, “137.35.2.5/32” or “prefix 137.35.2.5 mask 255.255.255.255” .
We should consider for next revision to add slight text in the draft just to specify which notation is allowed.

**Comment by lana-wu** [comment]
Here is the updated "value" for the "match-criterion":
       
 leaf-list value {
          type string;
          description
            "Describes the slice service match criteria, e.g.
             IP prefix, VLAN, etc.";
        }
And we can use “137.35.2.5/32” in some examples to show the use.

Do you think this is clearer?

**Comment by dhruvdhody** [comment]
In the yang types, ip-address and ip-prefix are also defined as strings with patterns. My suggestion would be that we stay close to that format only. We can state that in the text of the draft.   

Another option would be that for each identity for match-type, we can state the expected format of value in the description!

**Comment by sergiobelotti** [comment]
> In the yang types, ip-address and ip-prefix are also defined as strings with patterns. My suggestion would be that we stay close to that format only. We can state that in the text of the draft.
> 
> Another option would be that for each identity for match-type, we can state the expected format of value in the description!

Both options could be fine for me. Maybe the second appears more explicit and then preferable for me.

**Comment by sergiobelotti** [comment]
The new YANG version does NOT solve the issue as we discussed here in the comments. Dhruv proposed 2 solutions , neither of the two have been provide since what was done is just simply deleting
 
identity service-source-ip-match {
       base service-match-type;
       description
identity service-destination-ip-match {
       base service-match-type;
       description
         "Use destination ip-address in the packet header as
          match criteria for the slice service traffic.";
     }
and substitute with "prefix" 
identity service-source-ip-prefix-match {
    base service-match-type;
    description
      "Use source ip prefix as match criteria for
       the slice service traffic, e.g..";
  }

  identity service-destination-ip-prefix-match {
    base service-match-type;
    description
      "Use destination ip prefix as match criteria
       for the slice service traffic.";
  }

Maybe this could be acceptable but is not what we discussed above and precludes the possibility to use ip address. 
Issue#39 has proposed to "add" ip-prefix as match criteria not to delete the ip address.
For me the issue is still open.

**Comment by lana-wu** [comment]
@sergiobelotti  I think your previous suggestion makes sense, as The 32-bit host prefix and IP address are same. So why do we define repeatedly? e.g. “137.35.2.5/32” can be used for IP address case. 
Another point is L3SM also define this way:
[L3SM ](https://datatracker.ietf.org/doc/html/rfc8299#section-6)

`
                   |  |  |     |  +--:(match-flow)
                   |  |  |     |  |  +--rw match-flow
                   |  |  |     |  |     +--rw dscp?
                   |  |  |     |  |     |       inet:dscp
                   |  |  |     |  |     +--rw dot1p?              uint8
                   |  |  |     |  |     +--rw ipv4-src-prefix?
                   |  |  |     |  |     |       inet:ipv4-prefix
                   |  |  |     |  |     +--rw ipv6-src-prefix?
                   |  |  |     |  |     |       inet:ipv6-prefix
                   |  |  |     |  |     +--rw ipv4-dst-prefix?
                   |  |  |     |  |     |       inet:ipv4-prefix
                   |  |  |     |  |     +--rw ipv6-dst-prefix?
                   |  |  |     |  |     |       inet:ipv6-prefix
                   |  |  |     |  |     +--rw l4-src-port?
                   |  |  |     |  |     |       inet:port-number
                   |  |  |     |  |     +--rw target-sites*      svc-id
                   |  |  |     |  |     |       {target-sites}?
                   |  |  |     |  |     +--rw l4-src-port-range
                   |  |  |     |  |     |  +--rw lower-port?
                   |  |  |     |  |     |  |       inet:port-number
                   |  |  |     |  |     |  +--rw upper-port?
                   |  |  |     |  |     |          inet:port-number
                   |  |  |     |  |     +--rw l4-dst-port?
                   |  |  |     |  |     |       inet:port-number
                   |  |  |     |  |     +--rw l4-dst-port-range
                   |  |  |     |  |     |  +--rw lower-port?
                   |  |  |     |  |     |  |       inet:port-number
                   |  |  |     |  |     |  +--rw upper-port?
                   |  |  |     |  |     |          inet:port-number
                   |  |  |     |  |     +--rw protocol-field?     union
                   |  |  |     |  +--:(match-application)
                   |  |  |     |     +--rw match-application?
                   |  |  |     |             identityref`

**Comment by sergiobelotti** [comment]
I do not like the actual proposal to use service-source-ip-prefix-match and service-source-ip-prefix-destination for both ip address and ip prefix : this is NOT what required in issue #39 in which the prefix definition was required to be added to the ip-address.
I agree instead of Dhruv's options suggested about notation format : use string but with the  format definition described in RFC6021 , in which both ip-address and ip-prefix are defined as string but with pattern. This is the clean solution.
Here the example for ip-address , IPv4 
typedef ip-address {
     type union {
       type inet:ipv4-address;
       type inet:ipv6-address;
     }

 description
      "The ip-address type represents an IP address and is IP
       version neutral.  The format of the textual representations
       implies the IP version.";
   }

   typedef ipv4-address {
     type string {
       pattern
         '(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}'
       +  '([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
       + '(%[\p{N}\p{L}]+)?';
     }
     description
       "The ipv4-address type represents an IPv4 address in
        dotted-quad notation.  The IPv4 address may include a zone
        index, separated by a % sign.

        The zone index is used to disambiguate identical address
        values.  For link-local addresses, the zone index will
        typically be the interface index number or the name of an
        interface.  If the zone index is not present, the default
        zone of the device will be used.

        The canonical format for the zone index is the numerical
        format";
   }

You can choose one of the 2 options : either to add text in the draft saying that in the matching criteria value in case of ip-address or ip-prefix the notation format will follow what indicated in RFC6021 or add this note in the identities definitions for both ip-address and ip-prefix.

**Comment by lana-wu** [comment]
The model has followed the ACL YANG(RFC 8519 ) flow classification design. In ACL YANG, only prefixes are defined rather than “IP addresses”.
[https://datatracker.ietf.org/doc/html/rfc8519#section-3.1](url)
