### ISSUE TITLE
Joel's comment at IETF 116 on Isolation

### ISSUE THREAD

**Issue by dhruvdhody** [lana-wu/ietf-ns-nbi#49]
Joel has concerns about having Isolation in the YANG model esp -- "To be clear, my suggestion in the email exchange is to remove alll references to interference isolation. I understand others disagree. I have been clear in earlier emails why I am asking for this."

**Comment by lana-wu** [comment]
Following the definition in https://datatracker.ietf.org/doc/html/draft-ietf-teas-enhanced-vpn-15#name-requirements-on-traffic-iso, this document defines "service-traffic-isolation" identity to keep consistency:
https://datatracker.ietf.org/doc/draft-ietf-teas-ietf-network-slice-nbi-yang/08/
