### ISSUE TITLE
Med's point on importing RFC9181

### ISSUE THREAD

**Issue by dhruvdhody** [lana-wu/ietf-ns-nbi#5]
Hi Bo, all,

A discussion I had this morning with some colleagues that reminded me a comment made during the call of adoption vs. 9181. They prefer reusing as much as possible from stable modules.

I thus reiterate my comment to add an formal import of RFC9181 rather than grabbing some nodes for it. The import approach will also ease grafting the various pieces for those who will rely upon LxNMs to realize network slices.

For example, there is no need to redefine identity ns-connectivity-type as this maps what is in 9181, idem for endpoint-role. You can reuse service-status and many other nodes as the module is getting mature.

Thank you.

Cheers,
Med

**Comment by lana-wu** [comment]
Reuse the grouping definition of RFC9181 , including ‘vpn-common:service-status’, ‘vpn-common:vpn-topology'
https://datatracker.ietf.org/doc/draft-ietf-teas-ietf-network-slice-nbi-yang/02/
