### ISSUE TITLE
Need to update the reference to RFC8776-bis

### ISSUE THREAD

**Issue by italobusi** [lana-wu/ietf-ns-nbi#53]
The references to RFC8776 should be updated with a reference to RFC8776-bis (i.e., [I-D.ietf-teas-rfc8776-update]) at least when there is a dependency on the updates to RFC8776 provided in RFC8776-bis

See: https://mailarchive.ietf.org/arch/msg/teas/1XFx6vOG-A0iCkuv5DzVVft63o0/

**Comment by lana-wu** [comment]
After reviewing RFC8776-bis, it seems that RFC8776 already meets the definition of this document.
https://datatracker.ietf.org/doc/draft-ietf-teas-ietf-network-slice-nbi-yang/08/
