### ISSUE TITLE
Use reference statement

### ISSUE THREAD

**Issue by boucadair** [lana-wu/ietf-ns-nbi#55]
https://github.com/lana-wu/ietf-ns-nbi/blob/3023cf916661f7092df003dbd0319154925d9fe4/draft-ietf-teas-ietf-network-slice-nbi-yang.txt#L1632

For this one an similar, please consider using dedicated reference statements

**Comment by lana-wu** [comment]
Thanks for the suggestion. Has been addressed in https://datatracker.ietf.org/doc/draft-ietf-teas-ietf-network-slice-nbi-yang/08/
