### ISSUE TITLE
Med's & Greg's adding Statistical parameters

### ISSUE THREAD

**Issue by dhruvdhody** [lana-wu/ietf-ns-nbi#6]
Hi Greg,

 

(changing the subject so that this can be tracked by the authors of draft-ietf-teas-ietf-network-slice-nbi-yang)

 

Glad to see that we are in agreement about adding statistical parameters to the module. I hope that percentile values will be supported in the next iterations of the spec.

 

I like the spirit of the PAM SLO Draft. FWIW, please find some comments to the PAM SLO draft at these urls:

 

pdf: https://raw.githubusercontent.com/boucadair/IETF-Drafts-Reviews/master/draft-mhmcsfh-ippm-pam-00-rev%20Med.pdf
doc: https://github.com/boucadair/IETF-Drafts-Reviews/raw/master/draft-mhmcsfh-ippm-pam-00-rev%20Med.doc
 

Cheers,

Med

**Comment by lana-wu** [comment]
The NS service metric is defined as identity, which can be extended when there is a formal RFC.
